### ISSUE TITLE
为什么会用不到学习强国了？

### ISSUE THREAD

**Issue by dujianchi** [datehoer/studygoodcountry#5]
挺好奇的，这个不是一定要学的吗😂，因为啥忽然就用不到了？

**Comment by datehoer** [comment]
因为毕业了。
又不是党员也不是团员，只是为了完成学校的任务

dujianchi ***@***.***> 于2022年7月4日周一 10:15写道：

**Comment by dujianchi** [comment]
哦哦，原来如此
